import { useMemo, useState } from 'react';
import { AppShell } from '../components/AppShell';
import { ReferenceCard } from '../components/ReferenceCard';
import { ReferenceFilters } from '../components/ReferenceFilters';
import { SessionPreparation } from '../components/SessionPreparation';
import { categories, referenceStudies } from '../data/atelier-data';
import { emptyStudyFilters, filterStudies, type StudyFilters } from '../lib/filterStudies';
import type { ReferenceStudy } from '../types/content';

export function ExplorePage() {
  const [filters, setFilters] = useState<StudyFilters>(emptyStudyFilters);
  const [search, setSearch] = useState('');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [selectedStudy, setSelectedStudy] = useState<ReferenceStudy | null>(null);
  const results = useMemo(() => filterStudies(referenceStudies, filters, search), [filters, search]);
  const activeCount = Object.values(filters).flat().length;
  const toggle = (key: keyof StudyFilters, value: string) => setFilters((previous) => { const values = previous[key] as string[]; return { ...previous, [key]: values.includes(value) ? values.filter((item) => item !== value) : [...values, value] } as StudyFilters; });
  const subjectCategory = selectedStudy ? categories.find((category) => category.label === selectedStudy.subject) ?? categories[0] : null;
  return <AppShell><section className="reference-hero"><p className="eyebrow">Explore / Reference desk</p><h1>Find the study<br /><em>your hand needs.</em></h1><p>Choose one clear problem. Give it a little time. Make the work.</p><div className="reference-search"><label htmlFor="reference-search">Search references</label><input id="reference-search" placeholder="Try ‘hands’, ‘light’, or ‘perspective’" value={search} onChange={(event) => setSearch(event.target.value)} /></div></section><section className="quick-start" aria-label="Quick-start filters"><span>Start with</span>{['Portrait', 'Lighting', '20 minutes', 'Beginner'].map((option) => <button key={option} onClick={() => { const key = option === 'Portrait' ? 'subject' : option === 'Lighting' ? 'skill' : option === '20 minutes' ? 'time' : 'difficulty'; toggle(key, option as never); }}>{option}</button>)}</section><div className="reference-desk"><button className="mobile-filter-trigger" aria-expanded={filtersOpen} onClick={() => setFiltersOpen((open) => !open)}>Filters {activeCount > 0 && <span>{activeCount}</span>}</button><div className={`filter-drawer ${filtersOpen ? 'open' : ''}`}><ReferenceFilters filters={filters} onToggle={toggle} onClear={() => setFilters(emptyStudyFilters)} /></div><main className="reference-results"><header className="results-header"><div><p className="eyebrow">Your desk</p><h2>{results.length} {results.length === 1 ? 'study' : 'studies'} <span>to explore</span></h2></div><button className="sort-button">Best for you <span>⌄</span></button></header>{activeCount > 0 && <div className="active-filters" aria-label="Active filters">{Object.values(filters).flat().map((value) => <span key={value}>{value}</span>)}</div>}<p className="sr-only" role="status">{results.length} studies available</p>{results.length ? <div className="reference-grid">{results.map((study) => <ReferenceCard key={study.id} study={study} onStart={setSelectedStudy} />)}</div> : <section className="reference-empty"><p className="eyebrow">A clear desk</p><h2>No studies match this desk yet.</h2><p>Try widening your filter choices or begin with a short study.</p><button className="button button-dark" onClick={() => setFilters(emptyStudyFilters)}>Clear filters</button></section>}<section className="practice-nudge"><p className="eyebrow">A note from the studio</p><h2>One reference is enough to begin.</h2><p>Set a 20-minute timer and let the first study be only an observation.</p><button className="text-link">Start a focused session <span>↗</span></button></section></main></div>{selectedStudy && subjectCategory && <SessionPreparation category={subjectCategory} onClose={() => setSelectedStudy(null)} />}</AppShell>;
}
