import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { App } from './App';
import './styles/global.css';
import './styles/living-canvas.css';
import './styles/reference-desk.css';
import './styles/reference-rights.css';
import './styles/practice-workspace.css';
import './styles/practice-generator.css';
import './styles/challenge.css';
import './styles/compare.css';
import './styles/profile.css';
import './styles/community.css';
import './styles/cinema-home.css';
import './styles/opportunities.css';
import './styles/learning-paths.css';
import './styles/progress.css';
import './styles/master-studies.css';
import './styles/focused-inspiration.css';
import './styles/palette-lab.css';
import './styles/art-box.css';
import './styles/stuck-assistant.css';
import './styles/wip-critique.css';
import './styles/finish-piece.css';
import './styles/art-roulette.css';
import './styles/artist-rights.css';

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);
